kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml
- service.yaml
images:
- name: .*admin-ui.*
  newName: gcr.io/forgerock-io/platform-admin-ui/docker-build
  newTag: 7.4.0-9c6cd57fe26b2b2ec5c2273f6a1c1f60704a31ab
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: admin-ui
    app.kubernetes.io/name: admin-ui
    app.kubernetes.io/part-of: forgerock
    tier: ui
