apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ds-idrepo
spec:
  minAvailable: 1
  # maxUnavailable: 1 #Only one of minAvailable or maxUnavailable can be enabled.
  selector:
    matchLabels:
      app: ds-idrepo