# Patch IG
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ig
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      annotations:
        # prevent autoscaler from terminating the pod
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"