# Default override values for medium identity-platform cluster.

am:
  replicaCount: 3

  resources:
    limits:
      memory: 26Gi
    requests:
      cpu: 11000m
      memory: 26Gi

idm:
  replicaCount: 3

  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 8000m
      memory: 8Gi

ds_idrepo:
  replicaCount: 3

  resources:
    limits:
      memory: 29Gi
    requests:
      cpu: 8000m
      memory: 29Gi

  volumeClaimSpec:
    storageClassName: fast
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 512Gi

ds_cts:
  replicaCount: 3

  resources:
    limits:
      memory: 28Gi
    requests:
      cpu: 12000m
      memory: 28Gi

  volumeClaimSpec:
    storageClassName: fast
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1000Gi

