---
# Source: identity-platform/templates/ds-snapshot-rbac-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ds-snapshot
---
# Source: identity-platform/templates/platform-config-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  labels:
    helm.sh/chart: identity-platform-7.6
    app.kubernetes.io/name: identity-platform
    app.kubernetes.io/instance: identity-platform
    app.kubernetes.io/version: "7.6"
    app.kubernetes.io/managed-by: Helm
data:
  FORGEOPS_PLATFORM_SIZE: cdk
  FQDN: identity-platform.domain.local
  AM_URL: /am
  AM_ADMIN_URL: /am/ui-admin/
  IDM_ADMIN_URL: /admin
  IDM_UPLOAD_URL: /upload
  IDM_EXPORT_URL: /export
  PLATFORM_ADMIN_URL: /platform
  IDM_REST_URL: /openidm
  ENDUSER_UI_URL: /enduser
  LOGIN_UI_URL: /login/#/service/Login
  PLATFORM_UI_IS_FRAAS: "false"
  FRAAS_LOGGING_URL: ""
  ENDUSER_CLIENT_ID: end-user-ui
  ADMIN_CLIENT_ID: idm-admin-ui
  THEME: default
  AM_STORES_CTS_SERVERS: ds-cts-0.ds-cts:1636
  AM_STORES_USER_SERVERS: ds-idrepo-0.ds-idrepo:1636
  AM_SERVER_FQDN: identity-platform.domain.local
  AUTORESTORE_FROM_DSBACKUP: "false"
  DSBACKUP_DIRECTORY: ""
  DSBACKUP_HOSTS: ""
  DISASTER_RECOVERY_ID: "initial-restore"
  CERT_ISSUER: default-issuer
---
# Source: identity-platform/templates/ds-snapshot-rbac-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ds-snapshot
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
# Source: identity-platform/templates/ds-snapshot-rbac-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ds-snapshot
subjects:
  - kind: ServiceAccount
    name: ds-snapshot
    namespace: damon
roleRef:
  kind: ClusterRole
  name: ds-snapshot
  apiGroup: rbac.authorization.k8s.io
