apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intezer.fullname" . }}
  labels:
    {{- include "intezer.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- toYaml .Values.sensorConfig | nindent 4 }}
