apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intezer.fullname" . }}
  labels:
    {{- include "intezer.labels" . | nindent 4 }}
data:
  {{- if .Values.sensorConfig.license_key }}
  license_key: {{ .Values.sensorConfig.license_key | b64enc }}
  {{- else }}
  {{- required "***** .Values.sensorLicenseKey must not be empty!" .Values.sensorConfig.license_key }}
  {{- end }}
