name: Tag on merge
on:
  push:
    branches:
      - main
env:
  REGISTRY: "us-docker.pkg.dev"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set tag
        id: set_tag
        run: |
          echo "RELEASE_TAG=$(date +%Y.%m)" >> $GITHUB_ENV
          echo "BUILD_TAG=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Build
        id: bake
        uses: docker/bake-action@v5
        with:
          source: "{{defaultContext}}:docker"
          push: true
          files: |
            ./docker-bake.hcl

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Update chart version
        id: update_chart_version
        run: |
          sed -ie "s/^version:.*/version:\ $BUILD_TAG/" charts/identity-platform/Chart.yaml
          sed -ie "s/^appVersion:.*/appVersion:\ $BUILD_TAG/" charts/identity-platform/Chart.yaml

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts
          pages_branch: gh-pages

      - name: Create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.BUILD_TAG }}
          tag_prefix: ""

      - name: Create GitHub release
        id: create_github_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          #body: ${{ steps.tag_version.outputs.changelog }}
          bodyFile: CHANGELOG.md
          generateReleaseNotes: true
          makeLatest: true

      - name: Set helm chart URL
        id: set_helm_chart_url
        run: |
          echo "HELM_RELEASE_URL=${{ steps.create_github_release.outputs.html_url }}" | sed -e "s/$BUILD_TAG/identity-platform-$BUILD_TAG/" >>$GITHUB_ENV

      - name: Send Slack notification
        id: send_slack_notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            msg: "${{ steps.create_github_release.outputs.html_url }} $HELM_RELEASE_URL"

